### ISSUE TITLE
Crashes when no cert is found?

### ISSUE THREAD

**Issue by assetgrower** [nhalstead/Go-SSL-Fingerprint#1]
first off, thanks for putting this together.
It seems to crash when a cert is not found.  Could you possibly make it die more gracefully?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x401301]
goroutine 1 [running]:
panic(0x5f8020, 0xc4200120e0)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
main.getFingerprint(0x7fffd84d38a8, 0x8, 0x0, 0x0)
        /src/fingerprint.go:42 +0x211
main.main()
        //src/fingerprint.go:23 +0x4f
```

**Comment by assetgrower** [comment]
also, would it be possible to export the sha256 as well? I'd be happy to gittip

**Comment by nhalstead** [comment]
First Thanks for reporting this issues and thanks for the stack trace.

As far as returning a SHA256, I have it setup to return SHA1 (despite it having a SHA1 collision) as the fingerprint is still using SHA1 on a lot of system. It would not be hard to add SHA256 support, It would be a flag I would add `-sha256` or `-256`.

**Comment by assetgrower** [comment]
Awesome. Would be great if it had both as well and exported both

**Comment by nhalstead** [comment]
I will make it export SHA1 followed by the SHA256 hash.
Then to get one or the Other Hash you would use the flag `-sha256` or `-256` etc.

Should not be too hard.
I can have it updated in a few days when I get time for it.

**Comment by assetgrower** [comment]
Awesome. Thanks man!

**Comment by nhalstead** [comment]
Also was the server you were connecting to have the HTTPS Support? (Open Port of 443)
That may have been caused by the server not supporting the SSL, which would have caused the panic as `.TLS` does not exist?
The stack trace points to this [Line, #42](https://github.com/nhalstead/Go-SSL-Fingerprint/blob/master/src/fingerprint.go#L42).

**Comment by assetgrower** [comment]
Yes.  Some of the servers have https and others don't.  Would be nice if it
exited gracefully.
